# Generated by Django 2.1.7 on 2019-03-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_user', '0002_auto_20190323_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='img',
            field=models.ImageField(default=1, upload_to='places/'),
            preserve_default=False,
        ),
    ]
